# Generated by Django 4.2.11 on 2024-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('selling_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.TextField(verbose_name=200)),
                ('catagories', models.CharField(blank=True, max_length=2, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('composition', models.TextField()),
            ],
        ),
    ]
