# Generated by Django 5.1.7 on 2025-04-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderd',
            field=models.BooleanField(default=False),
        ),
    ]
