# Generated by Django 5.1.7 on 2025-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='catagory',
        ),
    ]
