# Generated by Django 4.2.11 on 2024-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0002_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='catagories',
            field=models.CharField(blank=True, choices=[('PN', 'pents'), ('ST', 'Shirts'), ('SO', 'Shoes'), ('SA', 'Sarees'), ('WA', 'Wallets')], max_length=2, null=True),
        ),
    ]
