# Generated by Django 5.1.7 on 2025-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0002_remove_productmodel_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.URLField(),
        ),
    ]
