# Generated by Django 5.1.7 on 2025-04-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0002_order_orderd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
