# Generated by Django 4.2.11 on 2024-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0003_alter_productmodel_catagories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
