# Generated by Django 5.1.7 on 2025-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0004_alter_productmodel_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.URLField(),
        ),
    ]
