# Generated by Django 5.1.7 on 2025-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0006_remove_order_amount_paid_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('cenceled', 'cenceled')], default='pending', max_length=233),
        ),
    ]
