# Generated by Django 4.2.11 on 2024-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0007_alter_productmodel_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='catagories',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='catagory',
            field=models.CharField(blank=True, choices=[('PNT', 'pents'), ('ST', 'Shirts'), ('SO', 'Shoes'), ('SA', 'Sarees'), ('WA', 'Wallets')], max_length=5, null=True),
        ),
    ]
