# Generated by Django 5.1.7 on 2025-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0010_remove_cartitem_user_alter_cart_update_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Orders'},
        ),
    ]
