# Generated by Django 4.2.11 on 2024-05-07 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alibaba', '0010_alter_customermodel_mobile_alter_customermodel_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
