# Generated by Django 5.1.7 on 2025-05-21 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0012_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
    ]
