# Generated by Django 5.1.7 on 2025-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0013_order_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_in_stock',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
