# Generated by Django 5.1.7 on 2025-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('S', 'stripe'), ('P', 'paypal'), ('COD', 'Cash on Delivery')], default='P', max_length=3),
        ),
    ]
