# Generated by Django 5.1.7 on 2025-06-05 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0018_alter_order_payment_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='ProfileModel',
        ),
    ]
