# Generated by Django 5.1.7 on 2025-06-05 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0019_rename_customermodel_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='location',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address_line1',
            field=models.CharField(default='jama masjid New Delhi', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profileImage'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
