# Generated by Django 5.1.7 on 2025-06-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0020_remove_profilemodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
