# Generated by Django 5.1.7 on 2025-06-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alibaba', '0021_profilemodel_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
